---
name: Test

on:
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        uses: docker/build-push-action@v1
        with:
          repository: djjudas21/tx-smtp-relay
          tags: testing
          push: false
